In [1]:
print("hello , interpreter ok")

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr*2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr = arr+"A"

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

In [7]:
# https://docs.scipy.org/doc/numpy/reference/ufuncs.html
# universal functions  for numpy array


In [8]:
arr[5]

5

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:6]
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_arr =arr[5:]


In [13]:
slice_arr

array([ 5,  6,  7,  8,  9, 10])

In [14]:
slice_arr[0:5]
slice_arr


array([ 5,  6,  7,  8,  9, 10])

In [15]:
slice_arr


array([ 5,  6,  7,  8,  9, 10])

In [16]:
slice_arr[5:]


array([10])

In [17]:
slice_arr


array([ 5,  6,  7,  8,  9, 10])

In [18]:
slice_arr = -99


In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_arr


-99

In [21]:
slice_arr

-99

In [22]:
arr_c = arr.copy()


In [23]:
arr_c[:]=102


In [24]:
arr_c


array([102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_2da = np.array([[10,20.30],[100,200.300],[1000,2000,3000]])


In [28]:
arr_2d


array([list([10, 20.3]), list([100, 200.3]), list([1000, 2000, 3000])],
      dtype=object)

In [30]:
arr_2d  +  1


TypeError: can only concatenate list (not "int") to list

In [32]:
arr_2da


array([list([10, 20.3]), list([100, 200.3]), list([1000, 2000, 3000])],
      dtype=object)

In [33]:
arr_2da[0,2]


IndexError: too many indices for array

In [36]:
arr_2da[0][1]


20.3

In [39]:
arr_2 = np.array( [[10,20.30], [100,200,300],[1000,2000,3000]])



In [38]:
arr_2

array([list([10, 20.3]), list([100, 200, 300]), list([1000, 2000, 3000])],
      dtype=object)

In [40]:
arr_2[1]


[100, 200, 300]

In [41]:
a3=arr_2[1]
a3[1]

200

In [42]:
arr_2[1][1]


200

In [43]:
print(arr_2)


[list([10, 20.3]) list([100, 200, 300]) list([1000, 2000, 3000])]


In [44]:
arr_2{:2}

SyntaxError: invalid syntax (<ipython-input-44-25b2826f2f09>, line 1)

In [47]:
arr_2[1:2,:1]

IndexError: too many indices for array

In [49]:
arr2 = np.arange(0,11)

In [50]:
    arr_2

array([list([10, 20.3]), list([100, 200, 300]), list([1000, 2000, 3000])],
      dtype=object)

In [51]:
arr_2

array([list([10, 20.3]), list([100, 200, 300]), list([1000, 2000, 3000])],
      dtype=object)

In [52]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
bool_arr = (arr2 > 2)


In [54]:
bool_arr


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
arr2[arr2 >2]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
print( len(arr2[arr2>2]))

8


In [61]:
print( len(arr2[arr2>2]))
print( arr2[arr2>2])

8
[ 3  4  5  6  7  8  9 10]


In [62]:
arr2d_b = np.arange(100).reshape(5,20)


In [63]:
arr2d_b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [66]:
arr2d_b = np.arange(100).reshape(20,5)

In [67]:
arr2d_b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [68]:
mat=np.arange(1,26).reshape(5,5)


In [69]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
mat.sum()

325

In [71]:
np.sum(mat)


325

In [73]:
mat.max()

25

In [74]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])