In [6]:
import numpy as np
import pandas as pd


In [1]:
print("hello, starting venv")

hello, starting venv


a list 


not an erray
https://www.pythoncentral.io/the-difference-between-a-list-and-an-array/


In [3]:
labels=['a','b','c']

In [8]:
labels


['a', 'b', 'c']

In [14]:
my_data =[10,20,30 ]
arr=np.array(my_data)

array via np wrapper 

In [10]:
arr2=np.array(my_data)
arr2

array([10, 20, 30])

In [11]:
arr2=arr2*2
arr2

array([20, 40, 60])

In [12]:
d={'a':10,'b':20,'c':30}
d

{'a': 10, 'b': 20, 'c': 30}

pd series concepts

In [16]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [17]:
#dictionary to series.. 
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [18]:
#list to  Series
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [20]:
#series can hold any data type , for example a list of strings as Data Points.. 
#series is a bunch of data points .
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [22]:
#series can hold set of  pointer to functions, like  C , very cool
pd.Series(data=[sum,print,len])


0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [25]:
#series  working  ,  ad hoc data and lablels
ser1 =pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [24]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [26]:
ser2 =pd.Series([1,2,4,5],['USA','Germany','Italy','Japan'])
ser2['USA']

1

In [27]:
#operations with 2 seres... if same index structure, then  operations are allowed
ser1+ser2

Germany    4.0
Italy      NaN
Japan      9.0
USA        2.0
USSR       NaN
dtype: float64

In [34]:
#on to dataframes- SETUP

# randn returns  N dim space  of random numbmers
from numpy.random import randn
np.random.seed(101)

In [30]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [33]:
randn(5,4,3,5)

array([[[[ 3.86030312e-01,  2.08401853e+00, -3.76518675e-01,
           2.30336344e-01,  6.81209293e-01],
         [ 1.03512507e+00, -3.11604815e-02,  1.93993231e+00,
          -1.00518692e+00, -7.41789705e-01],
         [ 1.87124522e-01, -7.32845148e-01, -1.38292010e+00,
           1.48249550e+00,  9.61458156e-01]],

        [[-2.14121229e+00,  9.92573453e-01,  1.19224064e+00,
          -1.04677954e+00,  1.29276458e+00],
         [-1.46751402e+00, -4.94095358e-01, -1.62534735e-01,
           4.85808737e-01,  3.92488811e-01],
         [ 2.21490685e-01, -8.55196041e-01,  1.54199041e+00,
           6.66319321e-01, -5.38234626e-01]],

        [[-5.68581361e-01,  1.40733825e+00,  6.41805511e-01,
          -9.05099902e-01, -3.91156627e-01],
         [ 1.02829316e+00, -1.97260510e+00, -8.66885035e-01,
           7.20787599e-01, -1.22308204e+00],
         [ 1.60677986e+00, -1.11570997e+00, -1.38537856e+00,
          -1.32966006e+00,  4.14599429e-02]],

        [[-4.11055403e-01, -7.71328605e-

In [44]:
randn(1,3)
pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>W</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>-0.116773</td>
      <td>1.901755</td>
      <td>0.238127</td>
      <td>1.996652</td>
    </tr>
    <tr>
      <th>B</th>
      <td>-0.993263</td>
      <td>0.196800</td>
      <td>-1.136645</td>
      <td>0.000366</td>
    </tr>
    <tr>
      <th>C</th>
      <td>1.025984</td>
      <td>-0.156598</td>
      <td>-0.031579</td>
      <td>0.649826</td>
    </tr>
    <tr>
      <th>D</th>
      <td>2.154846</td>
      <td>-0.610259</td>
      <td>-0.755325</td>
      <td>-0.346419</td>
    </tr>
    <tr>
      <th>E</th>
      <td>0.147027</td>
      <td>-0.479448</td>
      <td>0.558769</td>
      <td>1.024810</td>
    </tr>
  </tbody>
</table>
</div>

In [40]:
randn(1,10)

array([[ 0.50382575,  0.65111795, -0.31931804, -0.84807698,  0.60596535,
        -2.01816824,  0.74012206,  0.52881349, -0.58900053,  0.18869531]])

In [46]:
df1=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [47]:
df1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>W</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>0.992573</td>
      <td>1.192241</td>
      <td>-1.046780</td>
      <td>1.292765</td>
    </tr>
    <tr>
      <th>B</th>
      <td>-1.467514</td>
      <td>-0.494095</td>
      <td>-0.162535</td>
      <td>0.485809</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0.392489</td>
      <td>0.221491</td>
      <td>-0.855196</td>
      <td>1.541990</td>
    </tr>
    <tr>
      <th>D</th>
      <td>0.666319</td>
      <td>-0.538235</td>
      <td>-0.568581</td>
      <td>1.407338</td>
    </tr>
    <tr>
      <th>E</th>
      <td>0.641806</td>
      <td>-0.905100</td>
      <td>-0.391157</td>
      <td>1.028293</td>
    </tr>
  </tbody>
</table>
</div>

In [49]:
#how much ram 

df1.memory_usage()

Index    40
W        40
X        40
Y        40
Z        40
dtype: int64

In [51]:
#df is a bunch of series that share an index (in 2D case)

df1['W']


A    0.992573
B   -1.467514
C    0.392489
D    0.666319
E    0.641806
Name: W, dtype: float64

In [52]:
type(df1['W'])

pandas.core.series.Series

In [53]:
type(df1[['W','Z']])

pandas.core.frame.DataFrame

In [58]:
df1[['W','Z']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>W</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>0.992573</td>
      <td>1.292765</td>
    </tr>
    <tr>
      <th>B</th>
      <td>-1.467514</td>
      <td>0.485809</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0.392489</td>
      <td>1.541990</td>
    </tr>
    <tr>
      <th>D</th>
      <td>0.666319</td>
      <td>1.407338</td>
    </tr>
    <tr>
      <th>E</th>
      <td>0.641806</td>
      <td>1.028293</td>
    </tr>
  </tbody>
</table>
</div>

In [73]:
#really like a spreadsheet object  
df1['calcd']=df1['W']*100+df1['X']*100

In [74]:
df1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>W</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>calcd</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>0.992573</td>
      <td>1.192241</td>
      <td>-1.046780</td>
      <td>1.292765</td>
      <td>218.481409</td>
    </tr>
    <tr>
      <th>B</th>
      <td>-1.467514</td>
      <td>-0.494095</td>
      <td>-0.162535</td>
      <td>0.485809</td>
      <td>-196.160938</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0.392489</td>
      <td>0.221491</td>
      <td>-0.855196</td>
      <td>1.541990</td>
      <td>61.397950</td>
    </tr>
    <tr>
      <th>D</th>
      <td>0.666319</td>
      <td>-0.538235</td>
      <td>-0.568581</td>
      <td>1.407338</td>
      <td>12.808470</td>
    </tr>
    <tr>
      <th>E</th>
      <td>0.641806</td>
      <td>-0.905100</td>
      <td>-0.391157</td>
      <td>1.028293</td>
      <td>-26.329439</td>
    </tr>
  </tbody>
</table>
</div>

In [78]:
#very cool selectors 
df1.loc[ ['A','C'],['X','Y']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>X</th>
      <th>Y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>1.192241</td>
      <td>-1.046780</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0.221491</td>
      <td>-0.855196</td>
    </tr>
  </tbody>
</table>
</div>

In [83]:
#  by index numbers, indexing starts at 0  
df1.iloc[[0,2],[1,2]]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>X</th>
      <th>Y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>1.192241</td>
      <td>-1.046780</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0.221491</td>
      <td>-0.855196</td>
    </tr>
  </tbody>
</table>
</div>